# Generated by Django 5.1.1 on 2024-10-30 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False)),
                ('judul_film', models.CharField(max_length=100)),
                ('durasi', models.PositiveIntegerField(help_text='Durasi film dalam menit')),
                ('genre', models.CharField(max_length=50)),
                ('klasifikasi_umur', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('jam_tayang', models.TimeField()),
                ('studio', models.CharField(max_length=20)),
                ('harga_tiket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='jadwal.film')),
            ],
        ),
    ]
