# Generated by Django 5.1.1 on 2024-10-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='harga_tiket',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
